### PR TITLE
Use fileSystemRepresentation for files.

### PR DESCRIPTION
**Pull request by MaddTheSane**

### CODE REVIEW

**Comment by dirkz** [comment]
Thanks for the pull request. One request: Please replace strcpy with strlcpy if available. Will merge as soon as that is fixed.

**Comment by MaddTheSane** [comment]
Will do.

**Comment by akolade** [comment]
Wow, I wasn't expecting someone else to commit to iNethack! Looks like this is bringing the hearse log up to date with more proper file routines, correct?
I have some updates relating to iOS9 and a few new additions coming very soon.

**Comment by dirkz** [comment]
LOL, it's getting crowded :-)

**Pull request merged**
